//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalPortal.Api.Demo.Views.MeaningfulUses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPortal.Api.Demo.Views.MeaningfulUses.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Denominator {
            get {
                return ResourceManager.GetString("Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam date.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions qty.
        /// </summary>
        public static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaningful use.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure ID.
        /// </summary>
        public static string MeasureID {
            get {
                return ResourceManager.GetString("MeasureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        public static string Measures {
            get {
                return ResourceManager.GetString("Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure type.
        /// </summary>
        public static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 or 17.
        /// </summary>
        public static string MeasureTypes {
            get {
                return ResourceManager.GetString("MeasureTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Numerator {
            get {
                return ResourceManager.GetString("Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator qty.
        /// </summary>
        public static string NumeratorIDs {
            get {
                return ResourceManager.GetString("NumeratorIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective.
        /// </summary>
        public static string Objective {
            get {
                return ResourceManager.GetString("Objective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaningful uses.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient 1.
        /// </summary>
        public static string Patient1 {
            get {
                return ResourceManager.GetString("Patient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient 2.
        /// </summary>
        public static string Patient2 {
            get {
                return ResourceManager.GetString("Patient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient 3.
        /// </summary>
        public static string Patient3 {
            get {
                return ResourceManager.GetString("Patient3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting period end.
        /// </summary>
        public static string ReportingPeriodEnd {
            get {
                return ResourceManager.GetString("ReportingPeriodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting period start.
        /// </summary>
        public static string ReportingPeriodStart {
            get {
                return ResourceManager.GetString("ReportingPeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed?.
        /// </summary>
        public static string ResultPassed {
            get {
                return ResourceManager.GetString("ResultPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
