//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalPortal.Api.Client.GenericObject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiClientGenericObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiClientGenericObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPortal.Api.Client.GenericObject.ApiClientGenericObjectResources", typeof(ApiClientGenericObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Additional information: {0}.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/{0}{1}{2}{3}{4}.
        /// </summary>
        public static string DeleteRequestUri {
            get {
                return ResourceManager.GetString("DeleteRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/{0}{1}{2}{3}{4}.
        /// </summary>
        public static string GetRequestUri {
            get {
                return ResourceManager.GetString("GetRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must have a value..
        /// </summary>
        public static string IdNotNullable {
            get {
                return ResourceManager.GetString("IdNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/{0}.
        /// </summary>
        public static string PostRequestUri {
            get {
                return ResourceManager.GetString("PostRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/{0}{1}{2}.
        /// </summary>
        public static string SearchRequestUri {
            get {
                return ResourceManager.GetString("SearchRequestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response was unsuccessful. Status code: {0}..
        /// </summary>
        public static string UnsuccessfulResponseMessage {
            get {
                return ResourceManager.GetString("UnsuccessfulResponseMessage", resourceCulture);
            }
        }
    }
}
