//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalPortal.Api.Demo.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalPortal.Api.Demo.Views.Home.IndexResources", typeof(IndexResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our documentation section to access a quick guide or an in-depth reference of our API..
        /// </summary>
        public static string DocumentationDescription {
            get {
                return ResourceManager.GetString("DocumentationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download this demo.
        /// </summary>
        public static string DownloadDemo {
            get {
                return ResourceManager.GetString("DownloadDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the source code of this demo application. This package also includes the code of the helper library..
        /// </summary>
        public static string DownloadDemoDescription {
            get {
                return ResourceManager.GetString("DownloadDemoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the helper library.
        /// </summary>
        public static string DownloadHelperLibrary {
            get {
                return ResourceManager.GetString("DownloadHelperLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The helper library lets you write C# code to make HTTP requests to the Eye Reach Patients API..
        /// </summary>
        public static string DownloadHelperLibraryDescription {
            get {
                return ResourceManager.GetString("DownloadHelperLibraryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the documentation.
        /// </summary>
        public static string GoToDocumentation {
            get {
                return ResourceManager.GetString("GoToDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the list of services.
        /// </summary>
        public static string ListOfServices {
            get {
                return ResourceManager.GetString("ListOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a demo of how to use the Eye Reach Patients API. Click the links below to download the source code for this application as well as the source code for a helper library that uses the API..
        /// </summary>
        public static string SiteDescription {
            get {
                return ResourceManager.GetString("SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        public static string StartDownload {
            get {
                return ResourceManager.GetString("StartDownload", resourceCulture);
            }
        }
    }
}
